name: Build SoulsyHUD
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  VCPKG_COMMIT_ID: 93895b28ea7bc8cda10f156c5d336f3fc070f8b1

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create a github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SoulsyHUD ${{ github.ref }}
          draft: true
          prerelease: false

  compile:
    name: build plugin
    runs-on: windows-latest
    needs: [release]
    steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - uses: actions/cache@v3
          with:
              path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  target
              key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
              restore-keys: |
                  ${{ runner.os }}-cargo-
        - uses: ilammy/msvc-dev-cmd@v1.10.0
        - uses: lukka/run-vcpkg@v10.0
          with:
              vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

        - name: build
          uses: lukka/run-cmake@v10.0
          with:
              cmakeListsTxtPath: ${{ github.workspace }}/latest/CMakeLists.txt
              configurePreset: 'vs2022-windows'
              buildPreset: 'vs2022-windows'
              buildPresetAdditionalArgs: "['--config Release']"

        - name: build mod directory
          shell: bash
          run: |
              mkdir -p soulsyhud
              cp -r data/* soulsyhud/
              cp build/Release/SoulsyHUD.dll soulsyhud/SKSE/plugins/SoulsyHUD.dll
              cp build/Release/SoulsyHUD.pdb soulsyhud/SKSE/plugins/SoulsyHUD.pdb

        - name: 7zip compress it
          uses: edgarrc/action-7z@v1
          with:
            args: 7z a -t7z -mx=9 soulsyhud.7z ./soulsyhud/

        - name: upload mod 7z file
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{needs.release.outputs.upload_url}}
              asset_path: soulsyhud.7z
              asset_name: soulsyhud.7z
              asset_content_type: application/octet-stream
